idf_component_register(
    SRCS
        "src/audiobus.c"
        "src/audiobus_frame.c"
        "src/audiobus_discovery.c"
        "src/audiobus_tunnel.c"
        "src/phy/phy_lvds_oneic.c"
        "src/phy/phy_lvds_serdes.c"
        "src/codec/codec_8b10b.c"
        "src/net/abus_net.c"
        "src/net/abus_ptp.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        esp_driver_parlio
        esp_driver_gpio
        esp_eth
        esp_event
        esp_timer
        freertos
        esp_common
        esp_netif
        log
        heap
)
